const test = require("node:test");
const assert = require("node:assert/strict");
const { startRuntime } = require("./steering-runtime");
const cookie = response => response.headers.get("set-cookie").split(";")[0];
test("pilotage HTTP: route protection, session identity, exact-ID detail and private assets", async t => {
  const f = await startRuntime(); t.after(() => f.close());
  for (const route of ["metadata", "portfolio", "project"]) assert.equal((await f.request(`/api/odoo/pilotage/${route}`, { method: "POST", body: "{}" })).status, 401);
  const first = cookie(await f.login()), second = cookie(await f.login("second@example.com"));
  const post = (route, auth, body = {}) => f.request(`/api/odoo/pilotage/${route}`, { method: "POST", headers: { Cookie: auth }, body: JSON.stringify(body) });
  assert.equal((await f.request("/api/odoo/pilotage/portfolio", { headers: { Cookie: first } })).status, 405);
  assert.equal((await post("project", first, { projectId: "11" })).status, 400);
  const a = await (await post("portfolio", first, { uid: 8, apiKey: "attacker-key", unitDomain: [] })).json();
  const b = await (await post("portfolio", second)).json();
  assert.equal(a.projects.length, 2); assert.equal(a.projects[0].isLeader, true);
  assert.equal(b.projects.length, 1); assert.equal(b.projects[0].id, 12); assert.equal(b.projects[0].isLeader, true);
  assert.equal((await post("project", second, { projectId: 11 })).status, 404);
  assert.equal((await post("project", first, { projectId: 999 })).status, 404);
  const detail = await (await post("project", first, { projectId: 11 })).json();
  assert.equal(detail.project.diagnostic.progressActual, 120); assert.equal(detail.project.diagnostic.visibleActual, 30);
  assert.equal(detail.project.workPackages.status, "available");
  for (const file of ["steering.js", "steering-client.js", "steering-client.css"]) assert.equal((await f.request("/" + file, { headers: { Cookie: first } })).status, 200);
  assert.equal((await f.request("/steering-service.js", { headers: { Cookie: first } })).status, 404);
  assert.doesNotMatch(JSON.stringify(a) + JSON.stringify(b) + JSON.stringify(detail), /correct password|ignored-config-secret|attacker-key/);
  assert.ok(!f.calls.some(xml => xml.includes("<string>attacker-key</string>")));
  const before = f.calls.length;
  assert.equal((await f.request("/api/odoo/pilotage/portfolio", { method: "POST", headers: { Cookie: first, Origin: "https://attacker.test" }, body: "{}" })).status, 403);
  assert.equal(f.calls.length, before);
});
test("pilotage HTTP: disabled scope performs metadata only; denied planning stays partial", async t => {
  const disabled = await startRuntime({ disabled: true }); t.after(() => disabled.close());
  const auth = cookie(await disabled.login());
  const response = await disabled.request("/api/odoo/pilotage/portfolio", { method: "POST", headers: { Cookie: auth }, body: "{}" });
  const payload = await response.json(); assert.equal(payload.enabled, false);
  assert.ok(!disabled.calls.some(xml => xml.includes("<string>search_read</string>")));
  const denied = await startRuntime({ failModel: "planning.slot" }); t.after(() => denied.close());
  const second = cookie(await denied.login());
  const partial = await (await denied.request("/api/odoo/pilotage/portfolio", { method: "POST", headers: { Cookie: second }, body: "{}" })).json();
  assert.equal(partial.projects[0].hours.planned, null); assert.equal(partial.projects[0].hours.actual, 120);
  assert.doesNotMatch(JSON.stringify(partial), /private-upstream-secret/);
});
